spring.application.name=integration-service
spring.main.lazy-initialization=true
server.port=8080
logging.level.org.springframework.web=WARN
spring.mongodb.uri=mongodb+srv://amanxsays:kU7ftDyVQfihW2JP@namastenode.dfzkfmv.mongodb.net/devTinder
management.health.mongodb.enabled=false

google.gemini.api-key=${GEMINI_API_KEY}
pinecone.api-key=${PINECONE_API_KEY}
pinecone.index-name=devtinder-intelligence-hub


spring.data.redis.url=${REDIS_URL}
spring.data.redis.ssl.enabled=true
spring.mvc.async.request-timeout=600000
