spring.application.name=integration-service
spring.main.lazy-initialization=true
server.port=8080
logging.level.org.springframework.web=WARN
spring.mongodb.uri=mongodb+srv://amanxsays:kU7ftDyVQfihW2JP@namastenode.dfzkfmv.mongodb.net/devTinder

